spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/medbot_core
    username: konstantin
    password: secret
  jpa:
    show-sql: ${app.database.debug:false}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: medbot_core
        default_catalog: medbot_core
        show_sql: false
        format_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
  liquibase:
    default-schema: public
    change-log: "classpath:/db/changelog/changelog-master.yml"
    parameters:
      schema: medbot_core
      catalog: medbot_core
  application:
    name: medbot-core


server:
  port: 8787
  error:
    include-message : always

keycloak-admin:
  username: admin
  password: secret

keycloak:
  auth-server-url: http://127.0.0.1:8282/auth
  realm: demo
  resource: demo-app
  credentials:
    secret: 5a94408b-2b3d-4a10-af01-6dfc08bb3ab8
  ssl-required: none

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5672
